### ISSUE TITLE
Latest influxdb update breaking Pi-Hole-Monitoring on Raspberry Pi 4 32-bit Raspbian OS

### ISSUE THREAD

**Issue by suhasa010** [Brandawg93/Pi-Hole-Monitoring#28]
Reference: https://github.com/influxdata/influxdb/issues/20057#issuecomment-770440807

This is the error I get:

```
❯ docker-compose up -d
Creating network "pi-hole-monitoring_influxdb" with the default driver
Pulling influxdb (influxdb:latest)...
latest: Pulling from library/influxdb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Tried changing influxdb version in requirements.txt but it didn't work.

Please suggest.

**Comment by Brandawg93** [comment]
Looks like 1.8.4 was the last version to receive armv7 support. 

https://hub.docker.com/_/influxdb?tab=tags&page=1&ordering=last_updated

Change `latest` to `1.8.4`.

**Comment by Brandawg93** [comment]
This should be fixed in the latest pull. Thanks for the heads up.

**Comment by scottnzuk** [comment]
Still seeing this issue..


See 'docker run --help'.
pi@pirate:~ $ docker run --name influxdb -p 8086:8086 -v influxdb:/var/lib/influxdb influxdb
Unable to find image 'influxdb:latest' locally
latest: Pulling from library/influxdb
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.

OR

pi@pirate:~ $ sudo docker run --name influxdb -d -p 8086:8086 quay.io/influxdb/influxdb:v2.0.4
Unable to find image 'quay.io/influxdb/influxdb:v2.0.4' locally
v2.0.4: Pulling from influxdb/influxdb
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
pi@pirate:~ $ sudo docker run --name influxdb -d -p 8086:8086 quay.io/influxdb/influxdb:nightly
Unable to find image 'quay.io/influxdb/influxdb:nightly' locally
nightly: Pulling from influxdb/influxdb
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
pi@pirate:~ $
